### ISSUE TITLE
TypeError: object of type 'generator' has no len()

### ISSUE THREAD

**Issue by gizenmtl** [AghilesAzzoug/Artificial-Immune-System#2]
Hi AghilesAzzoug, 
First of all, I would like to mention that this repo is very useful for my project, so thank you so much for your contribution. But when I run main.py I got a error like this 

<img width="562" alt="Ekran Resmi 2019-12-19 20 07 34" src="https://user-images.githubusercontent.com/20821205/71193548-5801a700-229b-11ea-99d0-0caa6b27e277.png">

Could you help me please? Cause I didnt understand what I should do.

**Comment by AghilesAzzoug** [comment]
Hi,

I just ran the latest version (by adding a print after airs.train()) and everything is working correctly. It seems that your Python is considering the variable "ret" as a generator, what you can try is applying the "list" function on the "ret" variable, just like this : **ret = list([([float(x.split(",")[i]) for i in range(4)], mapping[x.split(",")[4][:-1]]) for x in content])**

Thanks for your attention by the way :)

**Comment by gizenmtl** [comment]
Yes, I added airs.train(), too. 
But now, I got different error. 

<img width="453" alt="Ekran Resmi 2019-12-19 20 58 28" src="https://user-images.githubusercontent.com/20821205/71197309-63a49c00-22a2-11ea-9e1b-efe1b6698202.png">

Do you know these reasons? I dont have any ideas.

Thanks, by the way :)

**Comment by AghilesAzzoug** [comment]
It seems that you replaced some of the square brackets with parentheses, just try to copy/paste this : 
**ret = list([([float(x.split(",")[i]) for i in range(4)], mapping[x.split(",")[4][:-1]]) for x in content])**

**Comment by gizenmtl** [comment]
When I write the code like this, it gives me this error. I don't understand why it makes such mistakes. But there are the same codes as you.

<img width="550" alt="Ekran Resmi 2019-12-19 22 57 17" src="https://user-images.githubusercontent.com/20821205/71205256-14b33280-22b3-11ea-9398-b76ad5b393f5.png">

AghilesAzzoug, please excuse me, I did not intend to engage you.

**Comment by AghilesAzzoug** [comment]
Try with the data file given on the repository (https://github.com/AghilesAzzoug/Artificial-Immune-System/blob/master/iris.data). 
No problems.

**Comment by gizenmtl** [comment]
Yes, it's solved. Thank you so much :) 
 I'll close issue.
