### ISSUE TITLE
Univariate analysis

### ISSUE THREAD

**Issue by esamanis** [AghilesAzzoug/Artificial-Immune-System#4]
Hello, thanks for the code seems interesting. How we can use it for univariate analysis? Can you explain how to add or remove features? Thanks

**Comment by AghilesAzzoug** [comment]
Hello, glad you found the code useful! 
Can you please elaborate what you mean by univariate analysis?

**Comment by esamanis** [comment]
Many thanks for the prompt reply! In your example, you are doing classification based on four features that define the class of a flower (Iris-setosa": 0, Iris-versicolor": 1, Iris-virginica": 2). I am trying to examine the applicability of this method classification based on one feature, i.e  ARRAY_SIZE = 1. Is that feasible?  (dataset looks like this): 

0.2,Iris-setosa
1.4,Iris-versicolor
2.1,Iris-virginica

Of course, this hypothetical scenario has meaning when we have unique values for each class. 

Also, same if we want to add more features i.e when ARRAY_SIZE > 4. What changes should we make? to achieve that? Use of more features vectors? Thanks!

**Comment by AghilesAzzoug** [comment]
Well, technically it is feasable. You will just have to change the Iris-related and hard-coded parameters like mutation methods where I manually specify the min/max for each feature or the mapping between index and class names. Except that, you wont have to change how the algorithm works. 
Feel free to submit a pull request if you manage to clean the code and make it more generalizable (I might do that once if I find some free time).

Hope it helps. Good luck!
